### ISSUE TITLE
The latest wsm versions are not compatible with XPrivacy, I use wsm 3.18 and everything works.

### ISSUE THREAD

**Issue by SWADED** [BurgerZ/WSM-Project#58]
The latest wsm versions are not compatible with XPrivacy, I use wsm 3.18 and everything works.

**Comment by SWADED** [comment]
java.lang.SecurityException: xuid=-1 calling=10080

Is the XPrivacy error

**Comment by zdunex25** [comment]
App Settings does not seem to work either:

Java.lang.NoSuchMethodError: de.robv.android.xposed.XposedHelpers.findFieldsByExactType
    at pro.burgerz.wsm.mods.mitools.b.dd.afterHookedMethod(Unknown Source)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:638)
    at com.android.systemui.statusbar.phone.PhoneStatusBar.a(Native Method)
    at com.android.systemui.statusbar.s.handleMessage(CommandQueue.java:276)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5050)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by BurgerZ** [comment]
I think this issue can be closed with 2.3.3 update.
